import { FilterSitesData } from '../../containers/email/types';

const dummyResponse: FilterSitesData[] = [
  {
    siteId: 3320197,
    address: '1002 Tremont St',
    adopterId: 2,
    adopterName: 'avery huang',
    adopterEmail: 'cassettememoir2010@gmail.com',
    dateAdopted: '2023-03-30',
    adopterActivityCount: 1,
    neighborhoodId: 16,
    lastActivityWeeks: 2,
  },
  {
    siteId: 3175985,
    address: 'Latino Student Culture Center',
    adopterId: 3,
    adopterName: 'truck man',
    adopterEmail: 'random@mail.com',
    dateAdopted: '',
    adopterActivityCount: 0,
    neighborhoodId: 34,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3276921,
    address: '',
    adopterId: 5,
    adopterName: 'truck man',
    adopterEmail: 'b@b.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 2,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3215644,
    address: '70–112 Gainsborough St',
    adopterId: 2,
    adopterName: 'avery huang',
    adopterEmail: 'cassettememoir2010@gmail.com',
    dateAdopted: '2023-03-30',
    adopterActivityCount: 10,
    neighborhoodId: 34,
    lastActivityWeeks: 2,
  },
  {
    siteId: 3300707,
    address: '590 E 8th St',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2022-10-17',
    adopterActivityCount: 0,
    neighborhoodId: 17,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3216138,
    address: '95 Westland Ave',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2023-01-24',
    adopterActivityCount: 0,
    neighborhoodId: 34,
    lastActivityWeeks: 14,
  },
  {
    siteId: 3210589,
    address: '522 Massachusetts Ave',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 32,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3321307,
    address: '',
    adopterId: 5,
    adopterName: 'truck man',
    adopterEmail: 'b@b.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 2,
    neighborhoodId: 11,
    lastActivityWeeks: 13,
  },
  {
    siteId: 3210590,
    address: '518 Massachusetts Ave',
    adopterId: 5,
    adopterName: 'truck man',
    adopterEmail: 'b@b.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 32,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3210588,
    address: '524 Chester Park',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 32,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3320197,
    address: 'dumb street',
    adopterId: 2,
    adopterName: 'avery huang',
    adopterEmail: 'cassettememoir2010@gmail.com',
    dateAdopted: '2023-03-30',
    adopterActivityCount: 1,
    neighborhoodId: 16,
    lastActivityWeeks: 2,
  },
  {
    siteId: 3175985,
    address: 'Latino Student Culture Center',
    adopterId: 3,
    adopterName: 'truck man',
    adopterEmail: 'random@mail.com',
    dateAdopted: '',
    adopterActivityCount: 0,
    neighborhoodId: 34,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3276921,
    address: '',
    adopterId: 5,
    adopterName: 'truck man',
    adopterEmail: 'b@b.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 2,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3215644,
    address: '70–112 Gainsborough St',
    adopterId: 2,
    adopterName: 'avery huang',
    adopterEmail: 'cassettememoir2010@gmail.com',
    dateAdopted: '2023-03-30',
    adopterActivityCount: 10,
    neighborhoodId: 34,
    lastActivityWeeks: 2,
  },
  {
    siteId: 3300707,
    address: '590 E 8th St',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2022-10-17',
    adopterActivityCount: 0,
    neighborhoodId: 17,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3216138,
    address: '95 Westland Ave',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2023-01-24',
    adopterActivityCount: 0,
    neighborhoodId: 34,
    lastActivityWeeks: 14,
  },
  {
    siteId: 3210589,
    address: '522 Massachusetts Ave',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 32,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3321307,
    address: '',
    adopterId: 5,
    adopterName: 'truck man',
    adopterEmail: 'b@b.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 2,
    neighborhoodId: 11,
    lastActivityWeeks: 13,
  },
  {
    siteId: 3210590,
    address: '518 Massachusetts Ave',
    adopterId: 5,
    adopterName: 'truck man',
    adopterEmail: 'b@b.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 32,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3210588,
    address: '524 Chester Park',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 32,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3320197,
    address: 'AAAAAAAAAAAAA',
    adopterId: 2,
    adopterName: 'avery huang',
    adopterEmail: 'cassettememoir2010@gmail.com',
    dateAdopted: '2023-03-30',
    adopterActivityCount: 1,
    neighborhoodId: 16,
    lastActivityWeeks: 2,
  },
  {
    siteId: 3175985,
    address: 'Latino Student Culture Center',
    adopterId: 3,
    adopterName: 'truck man',
    adopterEmail: 'random@mail.com',
    dateAdopted: '',
    adopterActivityCount: 0,
    neighborhoodId: 34,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3276921,
    address: '',
    adopterId: 5,
    adopterName: 'truck man',
    adopterEmail: 'b@b.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 2,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3215644,
    address: '70–112 Gainsborough St',
    adopterId: 2,
    adopterName: 'avery huang',
    adopterEmail: 'cassettememoir2010@gmail.com',
    dateAdopted: '2023-03-30',
    adopterActivityCount: 10,
    neighborhoodId: 34,
    lastActivityWeeks: 2,
  },
  {
    siteId: 3300707,
    address: '590 E 8th St',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2022-10-17',
    adopterActivityCount: 0,
    neighborhoodId: 17,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3216138,
    address: '95 Westland Ave',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2023-01-24',
    adopterActivityCount: 0,
    neighborhoodId: 34,
    lastActivityWeeks: 14,
  },
  {
    siteId: 3210589,
    address: '522 Massachusetts Ave',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 32,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3321307,
    address: '',
    adopterId: 5,
    adopterName: 'truck man',
    adopterEmail: 'b@b.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 2,
    neighborhoodId: 11,
    lastActivityWeeks: 13,
  },
  {
    siteId: 3210590,
    address: '518 Massachusetts Ave',
    adopterId: 5,
    adopterName: 'truck man',
    adopterEmail: 'b@b.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 32,
    lastActivityWeeks: undefined,
  },
  {
    siteId: 3210588,
    address: '524 Chester Park',
    adopterId: 4,
    adopterName: 'a b',
    adopterEmail: 'a@a.com',
    dateAdopted: '2022-11-13',
    adopterActivityCount: 0,
    neighborhoodId: 32,
    lastActivityWeeks: undefined,
  },
];

export default dummyResponse;
